### ISSUE TITLE
Cannot preview all 178 items in a folder

### ISSUE THREAD

**Issue by synox** [adobe/helix-sidekick-extension#476] opened 2023-08-08 00:21 UTC
**Description**
I have 178 documents in a folder. When I press 'select all' and then preview, it will only preview 60 documents. This is very confusing, as it shows as being successful. 

**To Reproduce**
1. Go to: https://adobe.sharepoint.com/:f:/r/sites/HelixProjects/Shared%20Documents/sites/24life/author?csf=1&web=1&e=vOKB5g 
2. Click on 'Toggle Selection for all items' in the Table Title bar
3. It shows "60 items selected"
4. Press `Copy URLS`, Preview
5. Observe that only 60 items are in the clipboard. 

Scrolling down selects more items, but not all. 

**Expected behavior**
All documents must be acted upon. 

**Screenshots**

<img width="431" alt="Screenshot 2023-08-07 at 17 20 15" src="https://github.com/adobe/helix-sidekick-extension/assets/2250964/066f0a7a-37ff-4790-9904-1cebc94f57b8">

**Comment by rofe** [comment] 2023-08-08 08:44
Duplicate of #228

**Closed by rofe** 2023-08-08 08:44 UTC
Labels: bug

**Comment by synox** [comment] 2023-08-08 16:14
@rofe yes it's the same issue. I think we should keep #228  open, as it is not fixed.
