### ISSUE TITLE
Sidekick does not open up for local port other than 3000

### ISSUE THREAD

**Issue by sdmcraft** [adobe/helix-sidekick-extension#288] opened 2023-03-17 11:03 UTC
**Description**
The sidekick doesn't open for me if I run my local hlx cli on a port other than `3000` like `hlx up --port 3001` 

**To Reproduce**
1. Run `hlx cli` on a non-standard port(3000) like `hlx up --port 3001`
2. Click on sidekick extension in browser.
3. Sidekick does not open up

**Expected behavior**
Sidekick should open up even when `hlx cli` is run with a port other than `3000`.

**Additional context**
this is hardcoded:
https://github.com/adobe/helix-sidekick-extension/blob/9084063356cf29c88010d2758caca4a48004bd8d/src/extension/module.js#L268

**Comment by rofe** [comment] 2023-03-28 05:57
Duplicate of #237

**Closed by rofe** 2023-03-28 05:57 UTC
Labels: bug
