### ISSUE TITLE
Persist the selection of a project

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-sidekick-extension#368] opened 2023-05-23 15:35 UTC
If you have multiple projects using the same mount points, you have to select which project you are working on. But when you reload the page, you have to select it again. We could persist the selection in the SessionStorage and only ask once per browsing session.

**Comment by rofe** [comment] 2023-05-25 08:57
Duplicate of #366

**Closed by rofe** 2023-05-25 08:57 UTC
Labels: enhancement
