### ISSUE TITLE
side kick not showing all the selected items

### ISSUE THREAD

**Issue by ravkiran** [adobe/helix-sidekick-extension#507] opened 2023-09-01 22:04 UTC
**Description**
When you select all the items in a folder in sharepoint, where there're 200+ documents, side kick is showing the selected count as wrong. I've selected 216 documents, by scrolling to the complete bottom, but side kick is only showing 116 selected. 
Please check the screenshot

**To Reproduce**
1. Go to Sharepoint folder where you've 200+ documents in one folder
2. Launch the side kick browser extension
3. Scroll to the complete bottom to load all the documents in the sharepoint view
4. Select all the documents using `Cmd + A` and observe that Sharepoint will select all the 200+ documents but the count in the side kick will show less number only.
5. This makes it difficult to run the bulk preview/publish functionality

**Expected behavior**
Side kick should show all the selected documents and allow to perform the bulk preview/publish actions.

**Screenshots**
<img width="1728" alt="image" src="https://github.com/adobe/helix-sidekick-extension/assets/1553152/ede50565-a689-44e5-baf8-75761511ab60">

**Comment by ravkiran** [comment] 2023-09-01 22:07
This is working fine when we do this in tiles view, but not working in List view

**Comment by rofe** [comment] 2023-09-02 08:57
This is a duplicate of #228, and unfortunately we don't have a solution for it yet. See #228 for more details.

> This is working fine when we do this in tiles view, but not working in List view

Interesting, it seems that the limit of 116 detected selected items seems to rise up to 259 in tiles view. Folders with more items will have the same issue though.

The only workaround I see is to preview/publish in batches of ~100.

**Closed by rofe** 2023-09-02 08:57 UTC
Labels: bug
