### ISSUE TITLE
[i18n] Some characters are not fully visible in input fields in Options

### ISSUE THREAD

**Issue by makarovan** [adobe/helix-sidekick-extension#645] opened 2024-01-09 10:02 UTC
**Description**
Some High ASCII / SEA characters are not fully visible in input fields in Options

**To Reproduce**
1. Install extension
2. Add new project to extension
3. Go to extension options > Advanced
4. Click on Edit button near project
5. Paste "ÄÂ" / " ျ ွ ြ ှ ေ ါ ် ာ ု ူ ံ ိ ီ ဲ င်္ ဿ ၏ ၌ ၍ ၎င်း" in input fields

**Expected behavior**
Characters are fully visible in input fields

**Screenshots**
![2024 01](https://github.com/adobe/helix-sidekick-extension/assets/90141516/c4f8d677-32ce-4716-b1bd-b5282e2beda1)

**Comment by rofe** [comment] 2024-01-10 15:30
What would be the use case for this? None of these special characters are allowed or processed, except in the project name field (1st field)

**Comment by Adobe-G11N-I18N-L10N-Team** [comment] 2024-01-11 06:48
@rofe Does the extension only supports 10 locales and their special characters? Â is french character and it is truncated in "Project Name" field

**Comment by rofe** [comment] 2024-01-12 06:21
I can't reproduce this...
<img width="147" alt="image" src="https://github.com/adobe/helix-sidekick-extension/assets/1609742/b097ba87-c93b-42f5-85f6-42304110572b">

**Comment by Adobe-G11N-I18N-L10N-Team** [comment] 2024-01-12 07:39
Seems like it depends on monitor diagonal, we reproduced it on 24'' monitor, but on 27'' its OK
![2](https://github.com/adobe/helix-sidekick-extension/assets/144205585/401d9009-8da7-456f-9cd4-a813962395a1)
<img width="639" alt="1" src="https://github.com/adobe/helix-sidekick-extension/assets/144205585/b44b4010-4976-448d-97e1-6572b75c4a24">

**Comment by rofe** [comment] 2024-01-12 08:10
I think this is an edge case affecting a very small number of users, if any. Resolving as wontfix.

**Closed by rofe** 2024-01-12 08:10 UTC
Labels: bug, wontfix, i18n
