### ISSUE TITLE
"Bulk" preview message on `.helix/config` is confusing

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-sidekick-extension#314] opened 2023-04-12 20:31 UTC
when selecting `.helix/config.xlsx` trying to bulk preview the following error message is shown.
i have also seen other error messages (eg. "illegal character in path").

<img width="957" alt="Screenshot 2023-04-12 at 2 29 33 PM" src="https://user-images.githubusercontent.com/5289336/231577222-23fa9d2c-2e39-47c5-9e67-1a4149c0aebd.png">

**Comment by rofe** [comment] 2023-04-12 20:38
I suspect there are potentially several combined issues at play here:
- wrong `webPath` status response from admin API: https://github.com/adobe/helix-sidekick-extension/issues/311 (waiting for fix in `helix-admin`)
- wrong "Illegal characters in path" message: https://github.com/adobe/helix-sidekick-extension/issues/299 (fixed in v6.12.3)

**Comment by rofe** [comment] 2023-04-12 20:41
Nope, it actually is its own distinct issue: the path is getting sanitized to 
`https://admin.hlx.page/preview/owner/repo/main/helix/config.json`

**Comment by rofe** [comment] 2023-04-12 20:46
But it's also caused by an erroneous admin status response:
```json
"webPath": "/helix"
```

**Closed** 2023-04-15 15:06 UTC
Labels: bug
