### ISSUE TITLE
Have a way to differentiate different repos on the same host via root path

### ISSUE THREAD

**Issue by chrischrischris** [adobe/helix-sidekick-extension#679] opened 2024-02-27 20:37 UTC
**Is your feature request related to a problem? Please describe.**
For sites that have multiple hlx tenants that share the same host, it's annoying that you have to choose the project every time you open sidekick on a page.  E.g: For www.adobe.com, there are 3 different repos depending on what path is being used.  It also makes it error prone for users who may click the wrong repo and then are confused when the Edit and Published buttons are greyed out.

**Describe the solution you'd like**
The ability to specify a host (www.adobe.com) and top level folder (/my-specific-repo) would allow for all pages starting with that path to automatically know what repo it maps to.

**Describe alternatives you've considered**
None that I can think of.

**Additional context**
N/A

**Comment by rofe** [comment] 2024-02-29 15:22
Duplicate of #639

**Closed by rofe** 2024-02-29 15:22 UTC
Labels: enhancement
