### ISSUE TITLE
[l10n] Unlocalized strings in Options > User Experience in Google Drive

### ISSUE THREAD

**Issue by makarovan** [adobe/helix-sidekick-extension#396] opened 2023-05-30 07:23 UTC
**Description**
Unlocalized checkbox labels in Options > User Experience

**To Reproduce**
1. Install AEM sidekick extension to Chrome browser https://chrome.google.com/webstore/detail/aem-sidekick/ccfggkjabjahcjoljmgmklhpaccedipo
3. Right Click on extension icon > Options > User experience

**Expected behavior**
Strings are localized:
Franklin editor first time user experience
Franklin preview first time user experience
Franklin live first time user experience
Franklin production first time user experience
Reload button update indicator
Publish button update indicator
User menu

**Additional context**
Strings are not present in Aladdin.

**Screenshots**
![user experience_de](https://github.com/adobe/helix-sidekick-extension/assets/90141516/3caa5482-1f9c-4c80-b364-091959eee06e)
![user experience_fr](https://github.com/adobe/helix-sidekick-extension/assets/90141516/1e715a0a-4187-4aa1-bcfe-644fab6abff7)

**Comment by rofe** [comment] 2023-06-16 17:45
Duplicate of #395

**Closed by rofe** 2023-06-16 17:45 UTC
Labels: bug, l10n

**Comment by makarovan** [comment] 2023-06-20 12:19
Issue is fixed, please refer to #403. Verified on 6.2023
